import type { IconType } from "react-icons";
import {
  SiCss3,
  SiDocker,
  SiExpress,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiLinux,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiReactquery,
  SiRedis,
  SiRedux,
  SiSocketdotio,
  SiSupabase,
  SiTailwindcss,
  SiTrpc,
  SiTypescript,
} from "react-icons/si";

import { DiDatabase } from "react-icons/di";
import {
  FaCode,
  FaCloud,
  FaAws,
  FaWindows,
} from "react-icons/fa";
import { SiApachekafka as FaKafka } from "react-icons/si";

// Map only the skills from the array to their corresponding icons
export const techLogos: Record<string, IconType> = {
  C: FaCode,
  "C++": FaCode,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  HTML: SiHtml5,
  CSS: SiCss3,
  "Node.js": SiNodedotjs,
  React: SiReact,
  "Next.js": SiNextdotjs,
  "Tailwind CSS": SiTailwindcss,
  Express: SiExpress,
  "Express.js": SiExpress,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  SQL: DiDatabase,
  Docker: SiDocker,
  Redis: SiRedis,
  Redux: SiRedux,
  "Socket.IO": SiSocketdotio,
  Linux: SiLinux,
  Windows: FaWindows,
  Git: SiGithub,
  GitHub: SiGithub,
  Cloudinary: FaCloud,
  AWS: FaAws,
  Supabase: SiSupabase,
  "Prisma ORM": SiPrisma,
  "Drizzle ORM": DiDatabase,
  Kafka: FaKafka,
  "Tanstack-Query": SiReactquery,
  "Agora SDK": FaCode,
  "Rough.js": FaCode,
  KindeAuth: FaCode,
}
